-- 11-1 연습용 테이블
CREATE TABLE DEPT_TCL
    AS SELECT*FROM DEPT;

SELECT * FROM DEPT TCL;

-- 11-2 입력 수정 삭제
INSERT INTO DEPT_TCL VALUES(50, 'DATABASE', 'SEOUL');

UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO=40;

DELETE FROM DEPT_TCL WHERE DNAME='RESEARCH';

SELECT * FROM DEPT_TCL;

-- 11-3 ROLLBACK
ROLLBACK;

-- 11-4 입력 수정 삭제
INSERT INTO DEPT_TCL VALUES(50, 'NETWORK', 'SEOUL');

UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO=20;

DELETE FROM DEPT_TCL WHERE DEPTNO=40;

SELECT * FROM DEPT_TCL;

-- 11-5 COMMIT
COMMIT;

-- 11-6 SQL PLUST와 세션 비교
SELECT*FROM DEPT_TCL;

-- 11-7 세션에서의 제거(SQLPLUS와 비교)
DELETE FROM DEPT_TCL
WHERE DEPTNO=50;

SELECT*FROM DEPT_TCL;

-- 11-8 COMMIT후 확인
COMMIT;
SELECT * FROM DEPT_TCL;

-- 11-9 테이블 확인(SQLPLUST 비교)
SELECT * FROM DEPT_TCL;

-- 11-10 LOCK 확인
UPDATE DEPT_TCL SET LOC='SEOUL'
WHERE DEPTNO=30;
SELECT*FROM DEPT_TCL;

-- 11-11 SQL*PLUS에 UPDATE
-- 11-12 ORACLE 에서 COMMIT SQL*PLUS에서의 변화 확인(HANG 상태)
COMMIT;

-- 11-13 세션별 테이블 변화
SELECT*FROM DEPT_TCL;

-- 11-14 SQL*PLUS COMMIT;
-- 11-15 DEVELOPER에서 확인
SELECT * FROM DEPT_TCL;

SELECT*FROM DEPT;
