--EX01 ALLEN과 같은 직책, 사원정보 부서정보 출력
SELECT JOB, E.EMPNO, E.ENAME, E.SAL, E.DEPTNO, D.DNAME
    FROM DEPT D, EMP E
    WHERE D.DEPTNO = E.DEPTNO AND JOB = (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN');
    
--EX02 전체 평균 급여보다 높은 급여를 받는 사원
--사원정보, 부서정보, 급여 등급정보
--급여가많은순, 같을경우 사원번호 오름차순
SELECT * FROM (SELECT * FROM EMP E WHERE SAL > (SELECT AVG(SAL) FROM EMP)) E
    LEFT OUTER JOIN DEPT D
        ON E.DEPTNO = D.DEPTNO
    LEFT OUTER JOIN SALGRADE S
        ON E.SAL BETWEEN S.LOSAL AND S.HISAL
    ORDER BY SAL DESC, EMPNO;
        
--EX03 10번 부서 근무하는 사원중 30번 부서에 존재하지 않는 직책을 가진 사원
SELECT EMPNO, ENAME, SAL, GRADE, E.JOB
    FROM EMP E
    INNER JOIN SALGRADE S
    ON E.SAL BETWEEN S.LOSAL AND S.HISAL
    WHERE E.JOB <> ALL (SELECT JOB FROM EMP WHERE DEPTNO=30);
    
--EX04 SALESMAN 최고 급여보다 높은 급여 사원정보, 급여등급 정보
SELECT EMPNO, ENAME, SAL, GRADE
    FROM EMP E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
        AND E.SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB = 'SALESMAN');
    

    