-- EX01
-- SAL 2000초과, 부서정보, 사원정보 , WHERE로 JOIN, JOIN문으로 JOIN 두경우
-- WHERE
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO
 AND SAL >2000;
 
-- JOIN
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E
JOIN DEPT D
ON D.DEPTNO = E.DEPTNO
WHERE SAL>2000;

-- EX02
-- 부서별 평균급여, 최대급여, 최소급여, 사원수
--WHERE
SELECT D.DEPTNO, D.DNAME, ROUND(AVG(SAL)) AVG_SAL, MAX(SAL) MAX_SAL, MIN(SAL) MIN_SAL , COUNT(*)
FROM EMP E, DEPT D
 WHERE E.DEPTNO=D.DEPTNO
GROUP BY D.DEPTNO, D.DNAME;

-- JOIN
SELECT DEPTNO, DNAME, ROUND(AVG(SAL)) AVG_SAL, MAX(SAL) MAX_SAL, MIN(SAL) MIN_SAL , COUNT(*)
FROM EMP E
JOIN DEPT D USING(DEPTNO)
GROUP BY DEPTNO, D.DNAME;

-- EX03
-- 모든 부서 정보와 사원 정보 부서번호, 사원이름순으로 출력
-- WHERE
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
    FROM EMP E, DEPT D
    WHERE D.DEPTNO = E.DEPTNO(+)
ORDER BY D.DEPTNO, E.ENAME;

--JOIN
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
    FROM DEPT D
    LEFT OUTER JOIN EMP E
    ON D.DEPTNO = E.DEPTNO
ORDER BY D.DEPTNO, E.ENAME;

-- EX04 
-- 모든 부서 정보, 사원정보, 급여 등급 정보, 각 사원의 직송산관 정보 출력
-- 부서번호 사원 본호 순 정렬
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.MGR, E.SAL, E.DEPTNO,
            S.LOSAL, S.HISAL, S.GRADE, E2.EMPNO MGR_EMPNO, E2.EMPNO MGR_ENAME
FROM DEPT D, EMP E, SALGRADE S, EMP E2
WHERE D.DEPTNO=E.DEPTNO(+) AND E.MGR = E2.EMPNO(+) AND E.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+)
ORDER BY D.DEPTNO, E.EMPNO;

--JOIN
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.MGR, E.SAL, E.DEPTNO,
            S.LOSAL, S.HISAL, S.GRADE, E2.EMPNO MGR_EMPNO, E2.EMPNO MGR_ENAME
FROM DEPT D
    LEFT OUTER JOIN EMP E
        ON E.DEPTNO = D.DEPTNO
    LEFT OUTER JOIN EMP E2
        ON E.MGR = E2.EMPNO
    LEFT OUTER JOIN SALGRADE S
        ON E.SAL BETWEEN S.LOSAL AND S.HISAL
ORDER BY D.DEPTNO, E.EMPNO;