-- 8-1 FROM 여러개 선언( , )로 나열 가능
SELECT *
    FROM EMP, DEPT
    ORDER BY EMPNO;
    
-- 8-2 열 이름을 이용한 조인
SELECT *
    FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO
    ORDER BY EMPNO;
    
-- 8-3 테이블 별칭
SELECT *
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    ORDER BY EMPNO;
    
-- 8.4 열 이름이 같을떄(어떤 테이블인지 명시필요
SELECT EMPNO, ENAME, DEPTNO, DNAME, LOC -- 어느 테이블의 DEPTNO인지 구분되지 않아 에러
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPT;
    
-- 8-5 열에 테이블명 명시
SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME, D.LOC
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    ORDER BY D.DEPTNO, E.EMPNO;
    
-- 8-6 WHERE 조건절 추가
SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME, D.LOC
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
        AND SAL >= 3000;
    
-- 8-7 범위 조건 조인(비등가방식)
SELECT *
    FROM EMP E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;
    
-- 8-8 SELF JOIN(같은 테이블로 조인)
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM EMP E1, EMP E2
    WHERE E1.MGR = E2.EMPNO;

-- 8-9 LEFT OUTER JOIN
SELECT 1.EMPNO, E1.ENAME, E1.MGR,
        E2. EMPNO AS MGR_EMPNO,
        E2. ENAME AS MGR_ENAME
    FROM EMP E1, EMP E2
    WHERE E1.MGR = E2.EMPNO(+)
    ORDER BY E1.EMPNO;
    
-- 8-10 RIGHT OUTER JOIN
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM EMP E1, EMP E2
    WHERE E1.MGR(+) = E2.EMPNO
    ORDER BY E1.EMPNO;
    
-- 8-11 NATURAL JOIN (공통 열에 테이블명 X, D.DEPTNO(x) -> DEPTNO(o))
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
        DEPTNO, D.DNAME, D.LOC
    FROM EMP E NATURAL JOIN  DEPT D
    ORDER BY DEPTNO, E.EMPNO;
    
-- 8-12 JOIN~USING( )
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
        DEPTNO, D.DNAME, D.LOC
    FROM EMP E JOIN DEPT D USING (DEPTNO)
    WHERE SAL>= 3000
    ORDER BY DEPTNO, E.EMPNO;
    
-- 8-13 JOIN ~ ON ( )
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
        E.DEPTNO, D.DNAME, D.LOC
    FROM EMP E JOIN DEPT D ON (E.DEPTNO=D.DEPTNO)
    WHERE SAL <= 3000
    ORDER BY E.DEPTNO, DEPTNO;

-- 8-14 LEFT OUTER JOIN
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM EMP E1 LEFT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    ORDER BY E1.EMPNO;
    
-- 8-15 RIGHT OUTER JOIN
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM EMP E1 
        RIGHT OUTER JOIN EMP E2
        ON E1.MGR = E2.EMPNO
    ORDER BY E1.EMPNO, MGR_EMPNO;
    
-- 8-16 FULL OUTER JOIN
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM EMP E1 
    FULL OUTER JOIN EMP E2 
    ON E1.MGR = E2.EMPNO
    ORDER BY E1.EMPNO;
    