-- 15-1,2 계정 생성 (SCOTT 계정으론 안됨) / SLQPLUS 이용 SYSTEM/oracle 접속하여 생성 가능
CREATE USER ORCLSTUDY IDENTIFIED BY ORACLE;

-- 15-3 접속을 위한 사용자 권한부여
GRANT CREATE SESSION TO ORCLSTUDY;

-- 15-4 패스워드 변경
ALTER USER ORCLSTUDY IDENTIFIED BY oracle;

-- 15-5 사용자 삭제
DROP USER ORCLSTUDY;

-- 15-6 사용자와 객체 모두 삭제하기
DROP USER ORCLSTUDY CASCADE;

-- 15-7 학습용 계정 재생성
CREATE USER ORCLSTUDY IDENTIFIED BY ORACLE;

-- 15-8 사용자 권한 부여(RESOURCE, CREATE SESSION, CREATE TABLE)
GRANT RESOURCE, CREATE SESSION, CREATE TABLE TO ORCLSTUDY;

-- 사용자 권한 취소 REVOKE [시스템 권한] FROM [사용자이름 /롤 / PUBLIC];

-- 15-9 다른 사용자에서 만든 테이블에 관한 객체 권한 부여(SCOTT 테이블 권한 -> ORCLSTUDY에게 부여)
CONN SCOTT/tiger;

CREATE TABLE TEMP(
    COL1 VARCHAR(20),
    COL2 VARCHAR(20)
);

GRANT SELECT ON TEMP TO ORCLSTUDY;
GRANT INSERT ON TEMP TO ORCLSTUDY;

-- 15-10 여러 권한 한번에 부여 ", " 이용
GRANT SELECT, INSERT ON TEMP TO ORCLSTUDY;

-- 15-11 부여받은 권한으로 다른 사용자 테이블 사용
CONN ORCLSTUDY/ORACLE;

SELECT * FROM SCOTT.TEMP;

INSERT INTO SCOTT.TEMP VALUES('TEXT', 'FROM ORCLSTUDY');

SELECT * FROM SCOTT.TEMP;

-- 15-12 부여된 객체 권한 취소하기
CONN SCOTT/tiger

REVOKE SELECT, INSERT ON TEMP FROM ORCLSTUDY;

-- 15-13 권한 취소 확인
CONN ORCLSTUDY/ORACLE

SELECT*FROM SCOTT.TEMP;

-- 15-14 롤 생성 
CONN SYSTEM/oracle

CREATE ROLE ROLESTUDY;  -- 롤 먼저 생성 이후 GRANT로 권한 부여

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM TO ROLESTUDY;

-- 15-15 유저에게 롤 부여
GRANT ROLESTUDY TO ORCLSTUDY;

-- 15-16 부여된 롤, 권한 확인
CONN ORCLSTUDY/ORACLE

SELECT*FROM USER_SYS_PRIVS;
SELECT*FROM USER_ROLE_PRIVS;