-- 14-1 NOT NULL 제약조건
CREATE TABLE TABLE_NOTNULL(
    LOGIN_ID VARCHAR2(20) NOT NULL,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20)
);

DESC TABLE_NOTNULL;

-- 14-2 NOT NULL 조건에 NULL INSERT - 오류
INSERT INTO TABLE_NOTNULL (LOGIN_ID, LOGIN_PWD, TEL)
    VALUES('TEST_ID_01', NULL, '010-1234-5678');
    
-- 14-3 제약 조건 없을경우 NULL 넣기
INSERT INTO TABLE_NOTNULL (LOGIN_ID, LOGIN_PWD)
    VALUES('TEST_ID_01', '1234');

SELECT*
FROM TABLE_NOTNULL;

-- 14-4 NOT NULL 조건 NULL로 UPDATE - 오류
UPDATE TABLE_NOTNULL
    SET LOGIN_PWD=NULL
    WHERE LOGIN_ID = 'TEST_ID_01';
    
-- 14-5 데이터 사전 USER_CONSTRAINTS 제약조건 확인 
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS;
    
-- 14-6 테이블 생성시 제약조건 이름 지정
CREATE TABLE TABLE_NOTNULL2(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLNM2_LGNID_NW NOT NULL,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLNM2_LGNPW_NM NOT NULL,
    TEL VARCHAR2(20)
);

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS;
    
-- 14-7 NOT NULL 제약 조건 추가(NULL이 이미 있는 열이라면?
ALTER TABLE TABLE_NOTNULL 
    MODIFY(TEL NOT NULL); --오류
    
-- 14-8 NULL 데이터 없는 부분 UPDATE
UPDATE TABLE_NOTNULL 
    SET TEL='010-1234-5678'
    WHERE LOGIN_ID = 'TEST_ID_01';

SELECT*FROM TABLE_NOTNULL;

-- 14-9 NULL이 없는 열 NOT NULL 제약 조건 추가
ALTER TABLE TABLE_NOTNULL
    MODIFY(TEL NOT NULL);
    
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS;
    
-- 14-10 제약조건에 이름 지정
ALTER TABLE TABLE_NOTNULL2
    MODIFY(TEL CONSTRAINT TBLNN_TEL_NN NOT NULL);
    
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS;
    
-- 14-11 TABLE_NOTNULL2 열 구조 확인
DESC TABLE_NOTNULL2;

-- 14-12 이미 생성된 제약조건 이름 변경
ALTER TABLE TABLE_NOTNULL2
    RENAME CONSTRAINT TBLNN_TEL_NN TO TBLNN2_TEL_NN;

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS;    
    
-- 14-13 제약 조건 삭제
ALTER TABLE TABLE_NOTNULL2
    DROP CONSTRAINT TBLNN2_TEL_NN;
    
DESC TABLE_NOTNULL2;


-- 14-14 UNIQUE 테이블 생성시 제약조건 지정 
CREATE TABLE TABLE_UNIQUE(
    LOGIN_ID VARCHAR2(20) UNIQUE,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20)
);

DESC TABLE_UNIQUE;

-- 14-15 제약 조건 확인 UNIQUE -> U, NOT NULL -> C, PRIMARY KEY -> P, FOREIGN KEY -> R
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'TABLE_UNIQUE';
    
-- 14-16 TABLE_UNIQE 데이터 입력
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
    VALUES('TEST_ID_01', 'PWD01', '010-1234-5678');
    
-- 14-17 UNIQUE 열값이 다른 행과 중복되는 경우 
INSERT INTO TABLE_UNIQUE (LOGIN_ID, LOGIN_PWD, TEL)
    VALUES('TEST_ID_01', 'PWD01', '010-1234-5678'); -- UNIQUE 제약 조건 위반 오류
    
-- 14-18 UNIQUE 제약 조건 열 값이 다르고 다른값은 같은 경우
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
    VALUES('TEST_ID_02', 'PWD01', '010-1234-5678');

SELECT*FROM TABLE_UNIQUE;

-- 14-19 UNIQUE 조건에 NULL값 INSERT -> 가능, 또한 NULL값은 중복 처리 안됨
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
    VALUES(NULL, 'PWD01', '010-2345-6789');
    
SELECT*FROM TABLE_UNIQUE;

-- 14-20 중복 데이터로 UNIQUE 값 수정 -> 오류
UPDATE TABLE_UNIQUE
    SET LOGIN_ID='TEST_ID_01'
    WHERE LOGIN_ID IS NULL;
    
-- 14-21 테이블 생성시 UNIQUE 제약조건 이름 설정
CREATE TABLE TABLE_UNIQUE2(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLUNQ2_LGNID_UNQ UNIQUE,
    LOGIN_PWD VARCHAR2(2) CONSTRAINT TBLUNQ2_LGNPW_NN NOT NULL,
    TEL VARCHAR2(20)
);

-- 14-22 생성한 제약조건 확인 UNIQUE -> U
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';
    
-- 14-23 이미 생성한열 제약 조건 추가 
ALTER TABLE TABLE_UNIQUE
MODIFY(TEL UNIQUE); -- 오류, 미리 입력된 열값이 UNIQUE 하지 않음

-- 14-24 NULL 값으로 UPDATE 
UPDATE TABLE_UNIQUE
    SET TEL = NULL;
    
SELECT*FROM TABLE_UNIQUE;

-- 14-25 UNIQUE 조건 설정(열 값이 NULL인 경우 중복 허용)
ALTER TABLE TABLE_UNIQUE
    MODIFY (TEL UNIQUE);

-- 14-26 제약조건 '이름' 지정하기 (UNIQUE 제약 조건을 주며 지정)
ALTER TABLE TABLE_UNIQUE2
MODIFY(TEL CONSTRAINT TBLUNQ_TEL_UNQ UNIQUE);

-- 14-27 제약조건 '이름' 변경(이미 UNIQUE 제약조건인경우)
ALTER TABLE TABLE_UNIQUE2
RENAME CONSTRAINT TBLUNQ_TEL_UNQ TO TBLUNQ2_TEL_UNQ;

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME LIKE'TABLE_UNIQUE%';
    
-- 14-28 제약 조건 삭제 ALTER + DROP CONSTRAINT
ALTER TABLE TABLE_UNIQUE2
DROP CONSTRAINT TBLUNQ2_TEL_UNQ;

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME LIKE'TABLE_UNIQUE%';
    
-- 14-29 테이블 생성시 PRIMARY KEY (NOT NULL + UNIQUE)
CREATE TABLE TABLE_PK(
    LOGIN_ID VARCHAR2(20) PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20)
);

DESC TABLE_PK;

-- 14-30 PRIMARY KEY 확인 -> P
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME LIKE 'TABLE_PK%';

-- 14-31 PRIMARY KEY 생성시 INDEX 자동 생성 -> 확인하기
SELECT INDEX_NAME, TABLE_OWNER, TABLE_NAME
    FROM USER_INDEXES
    WHERE TABLE_NAME LIKE 'TABLE_PK%';
    
-- 14-32 제약 조건 이름 지정
CREATE TABLE TABLE_PK2(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLPK2_LGNID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLPK2_LGNPW_NN NOT NULL,
    TEL VARCHAR2(20)
);

DESC TABLE_PK2;

-- 14-33 TABLE_PK 값 입력
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
    VALUES('TEST_ID_01','PWD01','010-1234-5678');

SELECT*FROM TABLE_PK;

-- 14-34 PK 중복되는 값 입력
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
    VALUES('TEST_ID_01','PWD02','010-2345-6789'); -- 오류
    
-- 14-35 NULL값 명시 입력
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
    VALUES(NULL, 'PWD02', '010-2345-6789'); -- 오류

-- 14-36 NULL값 암시 입력
INSERT INTO TABLE_PK(LOGIN_PWD, TEL)
    VALUES('PWD02', '010-2345-6789'); -- 오류
    
-- 14-37 EMP DEPT 제약 조건 R-> FOREIGN KEY
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, R_OWNER, R_CONSTRAINT_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME IN('EMP','DEPT');

-- 14-38 FOREIGN KEY가 참조하는 열에 존재하지 않는 데이터
INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES(9999,'홍길동','CLERK','7788',TO_DATE('2017/04/30', 'YYYY/MM/DD'), 1200, NULL, 50);
    -- 오류 DEPT를 참조하는 EMP의 FOREIGNY KEY 인 DEPTNO가 50인 경우 DEPT에 50인 열이 존재하지 않아 오류 
    
-- 14-39 실습용 DEPT 테이블 생성
CREATE TABLE DEPT_FK(
    DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13)
);

DESC DEPT_FK

-- 14-40 실습용 EMP 테이블 생성 FOREIGN KEY 지정 CONSTRAINT ~ REFERENCES
CREATE TABLE EMP_FK(
    EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
    ENAME  VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO)
);

-- 14-41 FOREIGN KEY 값이 얼을때 데이터 입력
INSERT INTO EMP_FK
    VALUES(9999, 'TEST_ENAME', 'TEST_JOB', NULL, TO_DATE('2001/01/01', 'YYYY/MM/DD'), 3000, NULL, 10); 
    -- 오류 FOREIGN KEY 값이 하나도 존재하지 않아서 참조가 안됨
    
-- 14-42 DEPT_FK에 데이터 삽입
INSERT INTO DEPT_FK
    VALUES(10, 'TEST_DNAME', 'TEST_LOC');
    
SELECT * FROM DEPT_FK;

-- 14-43 FOREIGN KEY 있을때 삽입
INSERT INTO EMP_FK
    VALUES(9999, 'TEST_ENAME', 'TEST_JOB', NULL, TO_DATE('2001/01/01', 'YYYY/MM/DD'), 3000, NULL, 10); 

SELECT * FROM EMP_FK;

-- 14-44 FOREIGN KEY값 삭제 -> 부모 테이블이 참조하고 있을때 제거 불가
DELETE FROM DEPT_FK
    WHERE DEPTNO=10;
    
-- 14-45 CHECK 제약조건
CREATE TABLE TABLE_CHECK(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK_LOGINID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLCK_LOGINPW_CK CHECK(LENGTH(LOGIN_PWD) > 3),
    TEL VARCHAR2(20)
);
 
 DESC TABLE_CHECK;
 
 -- 14-46 CHECK 제약 조건에 맞지 않을 경우 오류
 INSERT INTO TABLE_CHECK
    VALUES('TEST_ID', '123', '010-1234-5678');
    
-- 14-46 CHECK 제약 조건 지키고 입력 가능
INSERT INTO TABLE_CHECK
    VALUES('TEST_ID', '1234', '010-1234-5678');
    
SELECT * FROM TABLE_CHECK;

-- 14-47 데이터 사전 이용 CHECK 제약 조건 확인
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME LIKE 'TABLE_CHECK';
    
-- 14-48 DEFAULT 제약 조건
CREATE TABLE TABLE_DEFAULT(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK2_LOGINID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) DEFAULT '1234',
    TEL VARCHAR2(20)
);

DESC TABLE_DEFAULT;

-- 14-49 DEFAUL 값 입력 확인
INSERT INTO TABLE_DEFAULT VALUES('TEST_ID',NULL,'010-1234-5678'); --NULL 일 경우 DEFAULT값 아닌 NULL 값 입력

INSERT INTO TABLE_DEFAULT(LOGIN_ID, TEL) VALUES('TEST_ID2', '010-1234-5678'); -- 미입력시 DEFAULT

SELECT*FROM TABLE_DEFAULT;
