-- 12-1 CREATE TABLE
CREATE TABLE EMP_DDL(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),   /* 소숫점 이하 2자리 포함 7자리 작성 가능 => EX)12345.12 */
    DEPTNO NUMBER(2)
);

DESC EMP_DDL;

-- 12-2 열 구조가 같은 테이블 복사
CREATE TABLE DEPT_DDL
    AS SELECT * FROM DEPT;
    
-- 12-3 조회
SELECT * FROM DEPT_DDL;

-- 12-4 일부만 복사하여 테이블 생성
CREATE TABLE EMP_DDL_30
    AS SELECT*FROM EMP
        WHERE DEPTNO=30;

SELECT * FROM EMP_DDL_30;

-- 12-5 열구조만 복사한 새테이블 생성
CREATE TABLE EMPDEPT_DDL
    AS SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE,
                E.SAL, E.COMM, D.DEPTNO, D.DNAME, D.LOC
        FROM EMP E, DEPT D
        WHERE 1<>1;  /*언제나 FALSE 이용*/
        
SELECT * FROM EMPDEPT_DDL;

-- 12-6 ALTER 실습 테이블 생성
CREATE TABLE EMP_ALTER
    AS SELECT*FROM EMP;
    
SELECT*FROM EMP_ALTER;

-- 12-7 ALTER 열 추가
ALTER TABLE EMP_ALTER
    ADD HP VARCHAR2(20);

SELECT*FROM EMP_ALTER;

-- 12-8 RENAME 열 내임 변경
ALTER TABLE EMP_ALTER
    RENAME COLUMN HP TO TEL;

SELECT*FROM EMP_ALTER;

-- 12-9 MODIFY 자료형 변경
ALTER TABLE EMP_ALTER
MODIFY EMPNO NUMBER(5);

DESC EMP_ALTER;

-- 12-10 ALTER DROP 열 삭제
ALTER TABLE EMP_ALTER
DROP COLUMN TEL;

SELECT*FROM EMP_ALTER;

-- 12-11 테이블 이름 변경
RENAME EMP_ALTER TO EMP_RENAME;

-- 12-12 변경된 테이블 체크
DESC EMP_ALTER; -- 변겨되어서 에러

-- 12-13 변경 체크
DESC EMP_RENAME;

-- 12-14 데이터 삭제 (ROLLBACK 불가)
TRUNCATE TABLE EMP_RENAME;

SELECT*FROM EMP_RENAME;

-- 12-15 DROP TABLE(ROLLBACK 불가)
DROP TABLE EMP_RENAME;

-- 12-16 DROP 체크
DESC RENAME; -- 에러 존재안함