-- EX01 테이블 만들기

CREATE TABLE EMP_HW(
EMPNO NUMBER(4),
ENAME VARCHAR(10),
JOB VARCHAR(9),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2)
);

-- EX02 BIGO 열 추가, 가변 물자열 길이 20
ALTER TABLE EMP_HW
    ADD BIGO VARCHAR(20);
    
-- EX03 BIGO 열 크기 변경
ALTER TABLE EMP_HW
    MODIFY BIGO VARCHAR2(30);
    
-- EX04 열 이름 변경
ALTER TABLE EMP_HW
    RENAME COLUMN BIGO TO REMARK;
    
-- EX05 다른 테이블에서 열 값 가져오기
INSERT INTO EMP_HW
    (SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, NULL FROM EMP);

SELECT *FROM EMP_HW;

-- EX06
DROP TABLE EMP_HW;
    
    