--ORACLE에서 변수의 사용
--바인드(BIND) QUSTN

DROP USER SQLDB CASCADE;

CREATE USER SQLDB IDENTIFIED BY ORACLE
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT,RESOURCE, DBA TO SQLDB;

SET SERVEROUTPUT ON;
DECLARE
    MYVAR1 NUMBER(3);
    MYVAR2 NUMBER(5,2) := 3.14;
    MYVAR3 NVARCHAR2(20) := '본인의 키 ->';
                   --N -> 유니코드 의미
BEGIN
    MYVAR1 := 5;
    DBMS_OUTPUT.PUT_LINE(MYVAR1);
    DBMS_OUTPUT.PUT_LINE(MYVAR2);
    SELECT HEIGHT FROM USERTBL WHERE USERNAME='이승기';
    DBMS_OUTPUT.PUT_LINE(HEIGHT);
END;


-- 반복문
SET SERVEROUTPUT ON;
DECLARE
    INUM NUMBER(3);
    HAP NUMBER(5);
BEGIN
    INUM := 1;
    HAP := 0;
    WHILE INUM <= 100
    LOOP
        HAP := HAP+INUM;
        INUM := INUM+1;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(HAP);
END;



SET SERVEROUTPUT ON;
DECLARE
    INUM NUMBER(3);
    HAP NUMBER(5);
BEGIN
    HAP := 0;
    FOR INUM IN 1..100
    LOOP
        HAP := HAP+INUM;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(HAP);
END;

--1에서 100까지 합계에서 7의 배수는 합계에서 제외
SET SERVEROUTPUT ON;
DECLARE
    INUM NUMBER(3);
    HAP NUMBER(5);
BEGIN
    INUM := 1;
    HAP := 0;
    WHILE INUM <= 100
    LOOP
        IF MOD(INUM, 7) = 0 THEN 
        INUM := INUM+1;
        CONTINUE;
        END IF;
        HAP := HAP+INUM;
        IF HAP>1000 THEN
        EXIT;
        END IF;
        INUM := INUM+1;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(HAP);
END;

BEGIN
    DBMS_LOCK.SLEEP(5);
    DBMS_OUTPUT.PUT_LINE('5초간 멈춘 후 진행되었음');
END;

-- 예외처리
-- ORACLE 예외 : ORACLE 내부에 이미 


    