/*
문제
2015년 3월의 달력을 <표 1> 결과로 도출하는 MS SQL 쿼리를 작성하세요.

[표 1] 2015년 3월 달력
달력 만들기(MS SQL)
*/

WITH RECURSIVE CALENDAR AS (
  SELECT 1 DATENUM, '일' WEEK
  UNION ALL
  SELECT DATENUM+1 DATE 
       , CASE WHEN DATENUM%7+1 = 1 THEN '일'
              WHEN DATENUM%7+1 = 2 THEN '월'
              WHEN DATENUM%7+1 = 3 THEN '화'
              WHEN DATENUM%7+1 = 4 THEN '수'
              WHEN DATENUM%7+1 = 5 THEN '목'
              WHEN DATENUM%7+1 = 6 THEN '금'
              WHEN DATENUM%7+1 = 7 THEN '토'
              ELSE 0 END WEEK
    FROM CALENDAR
  WHERE DATENUM <= 30 
)
SELECT MAX(CASE WHEN WEEK = '일' THEN DATENUM END) AS '일'
     , MAX(CASE WHEN WEEK = '월' THEN DATENUM END) AS '월'
     , MAX(CASE WHEN WEEK = '화' THEN DATENUM END) AS '화'
     , MAX(CASE WHEN WEEK = '수' THEN DATENUM END) AS '수'
     , MAX(CASE WHEN WEEK = '목' THEN DATENUM END) AS '목'
     , MAX(CASE WHEN WEEK = '금' THEN DATENUM END) AS '금'
     , MAX(CASE WHEN WEEK = '토' THEN DATENUM END) AS '토'
  FROM CALENDAR WHERE DATENUM <= 7
UNION ALL
SELECT MAX(CASE WHEN WEEK = '일' THEN DATENUM END) AS '일'
     , MAX(CASE WHEN WEEK = '월' THEN DATENUM END) AS '월'
     , MAX(CASE WHEN WEEK = '화' THEN DATENUM END) AS '화'
     , MAX(CASE WHEN WEEK = '수' THEN DATENUM END) AS '수'
     , MAX(CASE WHEN WEEK = '목' THEN DATENUM END) AS '목'
     , MAX(CASE WHEN WEEK = '금' THEN DATENUM END) AS '금'
     , MAX(CASE WHEN WEEK = '토' THEN DATENUM END) AS '토'
  FROM CALENDAR WHERE DATENUM BETWEEN 8 AND 14
UNION ALL
SELECT MAX(CASE WHEN WEEK = '일' THEN DATENUM END) AS '일'
     , MAX(CASE WHEN WEEK = '월' THEN DATENUM END) AS '월'
     , MAX(CASE WHEN WEEK = '화' THEN DATENUM END) AS '화'
     , MAX(CASE WHEN WEEK = '수' THEN DATENUM END) AS '수'
     , MAX(CASE WHEN WEEK = '목' THEN DATENUM END) AS '목'
     , MAX(CASE WHEN WEEK = '금' THEN DATENUM END) AS '금'
     , MAX(CASE WHEN WEEK = '토' THEN DATENUM END) AS '토'
  FROM CALENDAR WHERE DATENUM BETWEEN 15 AND 21
UNION ALL
SELECT MAX(CASE WHEN WEEK = '일' THEN DATENUM END) AS '일'
     , MAX(CASE WHEN WEEK = '월' THEN DATENUM END) AS '월'
     , MAX(CASE WHEN WEEK = '화' THEN DATENUM END) AS '화'
     , MAX(CASE WHEN WEEK = '수' THEN DATENUM END) AS '수'
     , MAX(CASE WHEN WEEK = '목' THEN DATENUM END) AS '목'
     , MAX(CASE WHEN WEEK = '금' THEN DATENUM END) AS '금'
     , MAX(CASE WHEN WEEK = '토' THEN DATENUM END) AS '토'
  FROM CALENDAR WHERE DATENUM BETWEEN 22 AND 28
UNION ALL
SELECT MAX(CASE WHEN WEEK = '일' THEN DATENUM END) AS '일'
     , MAX(CASE WHEN WEEK = '월' THEN DATENUM END) AS '월'
     , MAX(CASE WHEN WEEK = '화' THEN DATENUM END) AS '화'
     , MAX(CASE WHEN WEEK = '수' THEN DATENUM END) AS '수'
     , MAX(CASE WHEN WEEK = '목' THEN DATENUM END) AS '목'
     , MAX(CASE WHEN WEEK = '금' THEN DATENUM END) AS '금'
     , MAX(CASE WHEN WEEK = '토' THEN DATENUM END) AS '토'
  FROM CALENDAR WHERE DATENUM >= 29