SELECT EMPLOYEE_ID, HIRE_DATE
FROM EMPLOYEES
ORDER BY HIRE_DATE ASC;

-- ROWNUM 행 번호
SELECT * FROM (SELECT EMPLOYEE_ID, HIRE_DATE
                    FROM EMPLOYEES
                    ORDER BY HIRE_DATE ASC)
                    WHERE ROWNUM <= 5;
                    
SELECT EMPLOYEE_ID, HIRE_DATE
    FROM EMPLOYEES
    WHERE ROWNUM <= 5;
    
--- 해당 테이블에서 n%의 데이터를 무작위로 추출 SAMPLE(N)
SELECT EMPLOYEE_ID, HIRE_DATE
FROM EMPLOYEES SAMPLE(5);

