다음은 식품의 정보를 담은 FOOD_PRODUCT 테이블입니다. FOOD_PRODUCT 테이블은 다음과 같으며 
PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE는 식품 ID, 식품 이름, 식품 코드, 식품분류, 식품 가격을 의미합니다.

Column name Type  Nullable
PRODUCT_ID  VARCHAR(10) FALSE
PRODUCT_NAME  VARCHAR(50) FALSE
PRODUCT_CD  VARCHAR(10) TRUE
CATEGORY  VARCHAR(10) TRUE
PRICE NUMBER TRUE

CREATE TABLE IF NOT EXISTS FOOD_PRODUCT (
  PRODUCT_ID VARCHAR(10) NOT NULL PRIMARY KEY,
  PRODUCT_NAME VARCHAR(50) NOT NULL,
  PRODUCT_CD VARCHAR(10),
  CATEGORY VARCHAR(10),
  PRICE INT
);

-- 테이블 확인
SELECT * FROM FOOD_PRODUCT;

-- 데이터 비우기
TRUNCATE FOOD_PRODUCT;

INSERT INTO FOOD_PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE) VALUES ('P0018', '맛있는고추기름', 'CD_OL00008', '식용유', 6100);
INSERT INTO FOOD_PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE) VALUES ('P0019', '맛있는카놀라유', 'CD_OL00009', '식용유', 5100);
INSERT INTO FOOD_PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE) VALUES ('P0020', '맛있는산초유',  'CD_OL00010', '식용유', 6500);
INSERT INTO FOOD_PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE) VALUES ('P0021', '맛있는케첩', 'CD_OL00001', '소스', 4500);
INSERT INTO FOOD_PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE) VALUES ('P0022', '맛있는마요네즈', 'CD_OL00002', '소스', 4700);

-- FOOD_PRODUCT 테이블에서 가격이 제일 비싼 식품의 식품 ID, 식품 이름, 식품 코드, 식품분류, 식품 가격을 조회하는 SQL문을 작성해주세요.
SELECT PRODUCT_ID
      ,PRODUCT_NAME
      ,PRODUCT_CD
      ,CATEGORY
      ,PRICE
  FROM FOOD_PRODUCT
 WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);