다음은 식당 리뷰 사이트의 회원 정보를 담은 MEMBER_PROFILE 테이블입니다. MEMBER_PROFILE 테이블은 다음과 같으며 
MEMBER_ID, MEMBER_NAME, TLNO, GENDER, DATE_OF_BIRTH는 회원 ID, 회원 이름, 회원 연락처, 성별, 생년월일을 의미합니다.

Column name Type  Nullable
MEMBER_ID VARCHAR(100)  FALSE
MEMBER_NAME VARCHAR(50) FALSE
TLNO  VARCHAR(50) TRUE
GENDER  VARCHAR(1)  TRUE
DATE_OF_BIRTH DATE  TRUE

CREATE TABLE IF NOT EXISTS MEMBER_PROFILE (
  MEMBER_ID VARCHAR(100) NOT NULL PRIMARY KEY,
  MEMBER_NAME VARCHAR(50) NOT  NULL,
  TLNO  VARCHAR(50), 
  GENDER  VARCHAR(1),
  DATE_OF_BIRTH DATE
);

-- 테이블 확인
SELECT * FROM MEMBER_PROFILE;

-- 데이터 비우기
TRUNCATE MEMBER_PROFILE;

INSERT INTO MEMBER_PROFILE (MEMBER_ID, MEMBER_NAME, TLNO, GENDER, DATE_OF_BIRTH) VALUES ('jiho92@naver.com', '이지호', '01076432111', 'W', '1992-02-12');
INSERT INTO MEMBER_PROFILE (MEMBER_ID, MEMBER_NAME, TLNO, GENDER, DATE_OF_BIRTH) VALUES ('jiyoon22@hotmail.com', '김지윤', '01032324117', 'W', '1992-02-22');
INSERT INTO MEMBER_PROFILE (MEMBER_ID, MEMBER_NAME, TLNO, GENDER, DATE_OF_BIRTH) VALUES ('jihoon93@hanmail.net', '김지훈', '01023258688', 'M', '1993-02-23');
INSERT INTO MEMBER_PROFILE (MEMBER_ID, MEMBER_NAME, TLNO, GENDER, DATE_OF_BIRTH) VALUES ('seoyeons@naver.com', '박서연', '01076482209', 'W', '1993-03-16');
INSERT INTO MEMBER_PROFILE (MEMBER_ID, MEMBER_NAME, TLNO, GENDER, DATE_OF_BIRTH) VALUES ('yoonsy94@gmail.com', '윤서연', NULL, 'W', '1994-03-19');

-- MEMBER_PROFILE 테이블에서 생일이 3월인 여성 회원의 ID, 이름, 성별, 생년월일을 조회하는 SQL문을 작성해주세요. 
-- 이때 전화번호가 NULL인 경우는 출력대상에서 제외시켜 주시고, 결과는 회원ID를 기준으로 오름차순 정렬해주세요.
SELECT MEMBER_ID
     , MEMBER_NAME
     , GENDER
     , DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d')
  FROM MEMBER_PROFILE
 WHERE DATE_FORMAT(DATE_OF_BIRTH, '%m') = 03
   AND GENDER = 'W'
   AND TLNO IS NOT NULL
 ORDER BY MEMBER_ID;