다음은 어느 의류 쇼핑몰의 온라인 상품 판매 정보를 담은 ONLINE_SALE 테이블 입니다. ONLINE_SALE 테이블은 아래와 같은 구조로 되어있으며
ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE는 각각 온라인 상품 판매 ID, 회원 ID, 상품 ID, 판매량, 판매일을 나타냅니다.

Column name Type  Nullable
ONLINE_SALE_ID  INTEGER FALSE
USER_ID INTEGER FALSE
PRODUCT_ID  INTEGER FALSE
SALES_AMOUNT  INTEGER FALSE
SALES_DATE  DATE  FALSE
동일한 날짜, 회원 ID, 상품 ID 조합에 대해서는 하나의 판매 데이터만 존재합니다.

CREATE TABLE IF NOT EXISTS ONLINE_SALE (
  ONLINE_SALE_ID INTEGER NOT NULL,
  USER_ID INTEGER NOT NULL,
  PRODUCT_ID INTEGER NOT NULL,
  SALES_AMOUNT INTEGER NOT NULL,
  SALES_DATE DATE NOT NULL
);

INSERT INTO ONLINE_SALE (ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE) VALUES (1, 1, 3, 2, '2022-02-25');
INSERT INTO ONLINE_SALE (ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE) VALUES (2, 1, 4, 1, '2022-03-01');
INSERT INTO ONLINE_SALE (ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE) VALUES (4, 2, 4, 2, '2022-03-12');
INSERT INTO ONLINE_SALE (ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE) VALUES (3, 1, 3, 3, '2022-03-31');
INSERT INTO ONLINE_SALE (ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE) VALUES (5, 3, 5, 1, '2022-04-03');
INSERT INTO ONLINE_SALE (ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE) VALUES (6, 2, 4, 1, '2022-04-06');
INSERT INTO ONLINE_SALE (ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE) VALUES (2, 1, 4, 2, '2022-05-11');

-- 테이블 확인
SELECT * FROM ONLINE_SALE;

-- 데이터 비우기
TRUNCATE ONLINE_SALE;

-- ONLINE_SALE 테이블에서 동일한 회원이 동일한 상품을 재구매한 데이터를 구하여, 재구매한 회원 ID와 재구매한 상품 ID를 출력하는 SQL문을 작성해주세요. 
-- 결과는 회원 ID를 기준으로 오름차순 정렬해주시고 회원 ID가 같다면 상품 ID를 기준으로 내림차순 정렬해주세요.
SELECT USER_ID
     , PRODUCT_ID
  FROM ONLINE_SALE
 GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(USER_ID)>1
 ORDER BY USER_ID, PRODUCT_ID DESC;

-- USER_INFO 테이블과 ONLINE_SALE 테이블에서 년, 월, 성별 별로 상품을 구매한 회원수를 집계하는 SQL문을 작성해주세요. 
-- 결과는 년, 월, 성별을 기준으로 오름차순 정렬해주세요. 이때, 성별 정보가 없는 경우 결과에서 제외해주세요.
SELECT DATE_FORMAT(OS.SALES_DATE, '%Y') YEAR
     , CONVERT(DATE_FORMAT(OS.SALES_DATE, '%c'), SIGNED INTEGER) MONTH
     , UI.GENDER
     , COUNT(DISTINCT OS.USER_ID) USERS
  FROM ONLINE_SALE OS
  JOIN USER_INFO UI ON OS.USER_ID = UI.USER_ID
 WHERE UI.GENDER IS NOT NULL
 GROUP BY YEAR, MONTH, UI.GENDER
 ORDER BY YEAR, MONTH, UI.GENDER;
 
-- DATE_FORMAT(OS.SALES_DATE, '%c') 을 사용할 경우 1,2,3 ---- 11, 12 로 표현된 월이 문자열로 비교되어 1, 11, 12, 2, 3 형태로 
-- 정렬되기때문에 CONVERT 함수를 이용하거나, MONTH() 등의 함수로 값을 정렬 시켜야한다.
