Column name Type  Nullable
USER_ID INTEGER FALSE
GENDER  TINYINT(1)  TRUE
AGE INTEGER TRUE
JOINED  DATE  FALSE

GENDER 컬럼은 비어있거나 0 또는 1의 값을 가지며 0인 경우 남자를, 1인 경우는 여자를 나타냅니다

CREATE TABLE IF NOT EXISTS USER_INFO (
  USER_ID INTEGER NOT NULL PRIMARY KEY,
  GENDER  TINYINT(1),
  AGE INTEGER,
  JOINED DATE NOT NULL
);

SELECT * FROM USER_INFO;
TRUNCATE USER_INFO;

INSERT INTO USER_INFO (USER_ID, GENDER, AGE, JOINED) VALUES (1, 1, 26, '2021-06-01');
INSERT INTO USER_INFO (USER_ID, GENDER, AGE, JOINED) VALUES (2, NULL, NULL, '2021-07-25');
INSERT INTO USER_INFO (USER_ID, GENDER, AGE, JOINED) VALUES (3, 1, NULL, '2021-07-30');
INSERT INTO USER_INFO (USER_ID, GENDER, AGE, JOINED) VALUES (4, 0, 31, '2021-08-03');
INSERT INTO USER_INFO (USER_ID, GENDER, AGE, JOINED) VALUES (5, 0, 28, '2021-12-16');
INSERT INTO USER_INFO (USER_ID, GENDER, AGE, JOINED) VALUES (6, 1, 24, '2022-01-03');
INSERT INTO USER_INFO (USER_ID, GENDER, AGE, JOINED) VALUES (7, 1, NULL, '2022-01-09');

-- USER_INFO 테이블에서 나이 정보가 없는 회원이 몇 명인지 출력하는 SQL문을 작성해주세요. 이때 컬럼명은 USERS로 지정해주세요.
SELECT COUNT(*) USERS
  FROM USER_INFO
 WHERE AGE IS NULL; 
 
-- USER_INFO 테이블에서 2021년에 가입한 회원 중 나이가 20세 이상 29세 이하인 회원이 몇 명인지 출력하는 SQL문을 작성해주세요.
SELECT COUNT(*) USERS
  FROM USER_INFO  
 WHERE AGE BETWEEN 20 AND 29
   AND JOINED BETWEEN '2021-01-01' AND '2021-12-31';